import React, { useEffect } from "react";
import { useDispatch } from "react-redux";
import { Container } from "react-bootstrap";
import { initializeScreen } from "../../api/Authentication";
import Catalog from "./GameCatalog/Catalog";
import Images from "./images";

function RulesScreen(props) {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(initializeScreen());
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="DesignerHelpScreen">
      <div id="side">
        <Catalog></Catalog>
      </div>
      <div id="main">
        <Container>
          <div className="Lexicon">
            {(function () {
              switch (props.type) {
                case "home":
                  return (
                    <div>
                      <h4>The Game</h4>
                      <p>
                        The game is set in a futuristic setting, where the two
                        player tries to control a newly explored area. They both
                        send robots to capture this ney territory. At the start
                        of the agme each player hasn a Command Center and some
                        starting resources. Their Goal is to be the first who
                        destroys the opponents Command Center.
                      </p>
                      <p>
                        The game is turn based, each unit has one action every
                        turn. If the game doesn't end in 100 turn the game is a
                        draw.
                      </p>
                    </div>
                  );
                case "resources":
                  return (
                    <div>
                      <h4>The Resources</h4>
                      <p>The game has 6 resource.</p>
                      <h4>Energy</h4>
                      <p>
                        Energy is needed for buildings to work. generated by
                        Solar Power Plants and the Command Center.
                      </p>
                      <h4>Steel</h4>
                      <p>
                        Steel is needed to build new buildings and used to make
                        RoboSteel. Produced by Steel Mines.
                      </p>
                      <h4>Crystal</h4>
                      <p>
                        Raw resource for Energy Cores. Produced by Core
                        Factories.
                      </p>
                      <h4>RoboSteel</h4>
                      <p>
                        Needed to build units. Produced in Foundries from steel.
                      </p>
                      <h4>Energy Core</h4>
                      <p>
                        Needed to build units. Produced in Core Factories from
                        crystals.
                      </p>
                      <h4>Credits</h4>
                      <p>
                        Act as money. Resources can be sold and bought using
                        credits.
                      </p>
                    </div>
                  );
                case "buildings":
                  return (
                    <div>
                      <h4>The Buildings</h4>
                      <p>
                        The game has 7 different buildings each with a different
                        purpose.
                      </p>
                      <h4>The Command Center</h4>
                      <img
                        src={Images.CommandCenter}
                        alt="Command Center"
                        width="100"
                        height="100"
                      ></img>
                      <p>
                        The Command center is the center of the base. It must be
                        protected. Your goal is to destroy your opponents
                        Command Center.
                      </p>
                      <h4>Steel Mine</h4>
                      <img
                        src={Images.SteelMine}
                        alt="Steel Mine"
                        width="100"
                        height="100"
                      ></img>
                      <p>
                        The Steel Mine produces steel. Must be placed on steel
                        ore.
                      </p>
                      <h4>Crystal Mine</h4>
                      <img
                        src={Images.CrystalMine}
                        alt="Crystal Mine"
                        width="100"
                        height="100"
                      ></img>
                      <p>
                        The Crystal Mine produces crystals. Must be placed on
                        crystal fields.
                      </p>
                      <h4>Solar Power Plant</h4>
                      <img
                        src={Images.SolarPowerPlant}
                        alt="Solar Power Plant"
                        width="100"
                        height="100"
                      ></img>
                      <p>Produces energy.</p>
                      <h4>Foundry</h4>
                      <img
                        src={Images.Foundry}
                        alt="Foundry"
                        width="100"
                        height="100"
                      ></img>
                      <p>The Foundry produces robosteel from steel.</p>
                      <h4>Core Factory</h4>
                      <img
                        src={Images.CoreFactory}
                        alt="Core Factory"
                        width="100"
                        height="100"
                      ></img>
                      <p>Produces energy cores from crystals.</p>
                      <h4>Workshop</h4>
                      <img
                        src={Images.Workshop}
                        alt="Workshop"
                        width="100"
                        height="100"
                      ></img>
                      <p>Needed for unit repair.</p>
                      <h4>Rubble</h4>
                      <img
                        src={Images.Rubble}
                        alt="Rubble"
                        width="100"
                        height="100"
                      ></img>
                      <p>
                        Not a building. Rubble symbolizes a destroyed building.
                        Stays for 3 turns, then disappers. No building can be
                        built on top of a Rubble.
                      </p>
                    </div>
                  );
                case "units":
                  return (
                    <div>
                      <h4>The Units</h4>
                      <p>
                        The game has 4 different units each with different
                        stats.
                      </p>
                      <h4>Attack Bot</h4>
                      <img
                        src={Images.Attack}
                        alt="Attack Bot"
                        width="100"
                        height="100"
                      ></img>
                      <p>The general attacking unit. Balanced stats.</p>
                      <p> Hit points: 16 </p>
                      <p> Attack damage: 8 </p>
                      <p> Armor: 3 </p>
                      <p> Range: 5 </p>
                      <p> Speed: 3 </p>
                      <h4>Artillery Bot</h4>
                      <img
                        src={Images.Artillery}
                        alt="Artillery Bot"
                        width="100"
                        height="100"
                      ></img>
                      <p>Long range, high damage unit. Has slow speed.</p>
                      <p> Hit points: 12 </p>
                      <p> Attack damage: 13 </p>
                      <p> Armor: 1 </p>
                      <p> Range: 6 </p>
                      <p> Speed: 2 </p>
                      <h4>Raider Bot</h4>
                      <img
                        src={Images.Raider}
                        alt="Raider Bot"
                        width="100"
                        height="100"
                      ></img>
                      <p>Fast attacking robot. Weaker defenses.</p>
                      <p> Hit points: 15 </p>
                      <p> Attack damage: 7 </p>
                      <p> Armor: 2 </p>
                      <p> Range: 4 </p>
                      <p> Speed: 4 </p>
                      <h4>Tank Bot</h4>
                      <img
                        src={Images.Tank}
                        alt="Tank Bot"
                        width="100"
                        height="100"
                      ></img>
                      <p>Strong defensive unit. Slow.</p>
                      <p> Hit points: 25 </p>
                      <p> Attack damage: 6 </p>
                      <p> Armor: 4 </p>
                      <p> Range: 4 </p>
                      <p> Speed: 2 </p>
                    </div>
                  );
                case "upgrades":
                  return (
                    <div>
                      <h4>The Upgrades</h4>
                      <p>
                        There are 4 upgrade types in the game. Each unit type
                        can be upgraded with all upgrade type once. The upgrades
                        only effect newly created units.
                      </p>
                      <h4>Attack Damage Upgrade</h4>
                      <p>
                        Increases the units attack by 1. Symbol: Target Cross.
                      </p>
                      <p> Upgrade Cost: 20 steel, 100 credits</p>
                      <h4>Armor Upgrade</h4>
                      <p>Increases the units armor by 1. Symbol: Shield.</p>
                      <p> Upgrade Cost: 20 steel, 100 credits</p>
                      <h4>Hit Points Upgrade</h4>
                      <p>
                        Increases the units hit points by 10. Symbol: Heart.
                      </p>
                      <p> Upgrade Cost: 50 steel, 50 credits</p>
                      <h4>Move Speed Upgrade</h4>
                      <p>
                        Increases the units move speed by 1. Symbol: Footprint.
                      </p>
                      <p>
                        {" "}
                        Upgrade Cost: 100 steel, 5 energy core, 100 credits
                      </p>
                    </div>
                  );

                default:
                  // return null;
                  return <div>{props.type}</div>;
              }
            })()}
          </div>
        </Container>
      </div>
    </div>
  );
}

export default RulesScreen;
